-- # 계정생성
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER kh04 IDENTIFIED BY khpwd;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE VIEW TO kh04;

-- # 게시판.sql 스크립트 실행

-- # SAMPLE DATA 삽입 - DDL

-- 특수기호& 대체입력문자 비활성화.
SET DEFINE OFF; 

-- # INSET 순서는 DROP 반대순서
--DROP TABLE "BOARD_REPLY";
--DROP TABLE "BOARD_REPORT";
--DROP TABLE "BOARD_FILE";
--DROP TABLE "LOGIN_LOG";
--DROP TABLE "BOARD";
--DROP TABLE "MEMBER";

-- # TABLE MEMEBER INSERT
--MEM_ID    NOT NULL VARCHAR2(20)  
--MEM_PWD   NOT NULL VARCHAR2(20)  
--MEM_EMAIL NOT NULL VARCHAR2(100)
CREATE OR REPLACE PROCEDURE PRO_MEMBER_INSERT
(   P_MEM_ID member.mem_id%TYPE,
    P_MEM_PWD member.mem_pwd%TYPE,
    P_MAXCOUNT NUMBER)
IS
BEGIN
    FOR I IN 1..P_MAXCOUNT LOOP
        INSERT INTO MEMBER VALUES
        (   P_MEM_ID||I,
            P_MEM_PWD,
            P_MEM_ID||I||'@KH.COM'
        );
    END LOOP;
END;
/
--계정 5개 생성 ID/PASSWORD/생성할 계정 수
EXEC PRO_MEMBER_INSERT('KH','PWD',5);
--SELECT * FROM MEMBER;

-- # TABLE BOARD INSERT
--BOARD_ID     NOT NULL NUMBER         
--SUBJECT      NOT NULL VARCHAR2(120)  
--CONTENT      NOT NULL VARCHAR2(4000) 
--WRITE_TIME   NOT NULL TIMESTAMP(6)   
--BOARD_WRITER NOT NULL VARCHAR2(20)   
--READ_COUNT   NOT NULL NUMBER         
--LOG_IP                VARCHAR2(15)
CREATE OR REPLACE PROCEDURE PRO_BOARD_INSERT
(   P_BOARD_SUBJECT BOARD.SUBJECT%TYPE,
    P_BOARD_CONTENT BOARD.CONTENT%TYPE,
    P_MEMBER_ID BOARD.BOARD_WRITER%TYPE,
    P_MAXCOUNT NUMBER)
IS
    V_B BOARD%ROWTYPE;
BEGIN
    FOR I IN 1..P_MAXCOUNT LOOP
        SELECT SEQ_BOARD_ID.NEXTVAL INTO V_B.BOARD_ID FROM DUAL;
        --V_B.BOARD_WRITER := P_MEMBER_ID;
        INSERT INTO BOARD VALUES
        (   V_B.BOARD_ID,
            P_BOARD_SUBJECT||I,
            P_BOARD_CONTENT||I,
            DEFAULT,
            P_MEMBER_ID,
            DEFAULT,
            '127.0.0.1');
    END LOOP;
END;
/
--SELECT SEQ_BOARD_ID.NEXTVAL FROM DUAL;
--CREATE SEQUENCE "SEQ_BOARD_ID";
--DROP SEQUENCE SEQ_BOARD_ID;
--게시글 5개 생성 - SEQ_BOARD_ID 사용 제목/본문/작성자/생성할 게시글 수
EXEC PRO_BOARD_INSERT('제목','게시글','KH1', 3);
EXEC PRO_BOARD_INSERT('제목','게시글','KH2', 2);
EXEC PRO_BOARD_INSERT('제목','게시글','KH5', 1);
--SELECT * FROM BOARD;
--TRUNCATE TABLE BOARD;

-- # TABLE LOGIN_LOG INSERT
--LOG_TIME NOT NULL TIMESTAMP(6) 
--LOG_IP   NOT NULL VARCHAR2(15) 
--MEM_ID   NOT NULL VARCHAR2(20) 
--LOG_TYPE NOT NULL CHAR(1)      

-- # TABLE BOARD_FILE INSERT
--BOARD_FILE_ID        NOT NULL NUMBER(5)      
--BOARD_ID             NOT NULL NUMBER         
--SAVED_FILE_PATH_NAME NOT NULL VARCHAR2(1000) 
--ORIGINAL_FILENAME    NOT NULL VARCHAR2(300)  

-- # TABLE BOARD_REPORT INSERT
--MEM_ID   NOT NULL VARCHAR2(20) 
--BOARD_ID NOT NULL NUMBER       

-- # TABLE BOARD_REPLY INSERT
--BOARD_REPLY_ID         NOT NULL NUMBER         
--BOARD_ID               NOT NULL NUMBER         
--BOARD_REPLY_WRITER     NOT NULL VARCHAR2(20)   
--BOARD_REPLY_CONTENT    NOT NULL VARCHAR2(4000) 
--BOARD_REPLY_WRITE_TIME NOT NULL TIMESTAMP(6)   
--BOARD_REPLY_LOG_IP              VARCHAR2(15)   
--BOARD_REPLY_LEVEL      NOT NULL NUMBER(2)      
--BOARD_REPLY_REF        NOT NULL NUMBER         
--BOARD_REPLY_STEP       NOT NULL NUMBER(3)      
